import esbuild from "esbuild";
import process from "process";
import { chmodSync } from "fs";
import builtins from "builtin-modules";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/main.js",
});

const cliOptions = {
    banner: {
        js: "#!/usr/bin/env node\n",
    },
    entryPoints: ["cli.ts"],
    bundle: true,
    platform: "node",
    target: "node18",
    format: "cjs",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/cli.js",
};

function markCliExecutable() {
    chmodSync("dist/cli.js", 0o755);
}

if (prod) {
    await context.rebuild();
    await esbuild.build(cliOptions);
    markCliExecutable();
    process.exit(0);
} else {
    const cliContext = await esbuild.context(cliOptions);
    await context.watch();
    await cliContext.watch();
    markCliExecutable();
}
